### ISSUE TITLE
World DB

### ISSUE THREAD

**Issue by beleavschi-ladela** [RuinOzenu/WowSource434#3]
Hi, where i can find world db?
Thanks

**Comment by JunkyBulgaria** [comment]
from his repack

**Comment by DencelF** [comment]
Hi Junky. Sorry for me bad english, but Updates which have World. The Olds only?

**Comment by JunkyBulgaria** [comment]
no idea mate, im just sharing this source, not giving any support on it

**Comment by DencelF** [comment]
Ok Thanks.
